name: Build dev-container

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: take-me-home-dev-container
  DOCKER_USER: benekenobi

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Install dev-container-cli
        run: npm install -g @vscode/dev-container-cli
      
      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v1

      - name: Build dev-container
        run: devcontainer build --image-name ${{ env.IMAGE_NAME }} ./devcontainer_src

      - name: Tag image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest

      - name: Docker login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push
        run: docker push ${{ env.REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
