name: Publish
concurrency: publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish-expo:
    name: Publish to Expo.dev
    environment: 
      name: expo
      url: https://expo.dev/@benekenobi/take-me-home
    env:
      GOOGLE_API_KEY_ANDROID: ${{ secrets.GOOGLE_API_KEY_ANDROID }}
      GOOGLE_API_KEY_IOS: ${{ secrets.GOOGLE_API_KEY_IOS }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Expo publish
        run: expo publish
  publish-web:
    name: Publish to GitHub Pages
    environment: 
      name: github-pages
      url: https://benekenobi.github.io/take-me-home/
    env:
      GOOGLE_API_KEY_WEB: ${{ secrets.GOOGLE_API_KEY_WEB }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Build web
        run: expo build:web
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: web-build
          jekyll: false
          commit_message: "chore: 🚀 deploy to GitHub pages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
