name: Lint
on: 
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Run linter
      uses: wearerequired/lint-action@v1
      with:
        eslint: true
        eslint_extensions: js,ts,jsx,tsx
