name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Run ESLint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx --output-file eslint_report.json --format json
      continue-on-error: true
    - name: Annotate code linting results
      uses: ataylorme/eslint-annotate-action@1.2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        report-json: "eslint_report.json"
    - name: Upload ESLint report
      uses: actions/upload-artifact@v2
      with:
        name: eslint_report.json
        path: eslint_report.json
